/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MembersIdRouteImport } from './routes/members.$id'
import { Route as MembersIdIndexRouteImport } from './routes/members.$id.index'
import { Route as MembersIdEditRouteImport } from './routes/members.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIdRoute = MembersIdRouteImport.update({
  id: '/members/$id',
  path: '/members/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIdIndexRoute = MembersIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MembersIdRoute,
} as any)
const MembersIdEditRoute = MembersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => MembersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/members/$id': typeof MembersIdRouteWithChildren
  '/members/$id/edit': typeof MembersIdEditRoute
  '/members/$id/': typeof MembersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/members/$id/edit': typeof MembersIdEditRoute
  '/members/$id': typeof MembersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/members/$id': typeof MembersIdRouteWithChildren
  '/members/$id/edit': typeof MembersIdEditRoute
  '/members/$id/': typeof MembersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/members/$id' | '/members/$id/edit' | '/members/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/members/$id/edit' | '/members/$id'
  id: '__root__' | '/' | '/members/$id' | '/members/$id/edit' | '/members/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MembersIdRoute: typeof MembersIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$id': {
      id: '/members/$id'
      path: '/members/$id'
      fullPath: '/members/$id'
      preLoaderRoute: typeof MembersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$id/': {
      id: '/members/$id/'
      path: '/'
      fullPath: '/members/$id/'
      preLoaderRoute: typeof MembersIdIndexRouteImport
      parentRoute: typeof MembersIdRoute
    }
    '/members/$id/edit': {
      id: '/members/$id/edit'
      path: '/edit'
      fullPath: '/members/$id/edit'
      preLoaderRoute: typeof MembersIdEditRouteImport
      parentRoute: typeof MembersIdRoute
    }
  }
}

interface MembersIdRouteChildren {
  MembersIdEditRoute: typeof MembersIdEditRoute
  MembersIdIndexRoute: typeof MembersIdIndexRoute
}

const MembersIdRouteChildren: MembersIdRouteChildren = {
  MembersIdEditRoute: MembersIdEditRoute,
  MembersIdIndexRoute: MembersIdIndexRoute,
}

const MembersIdRouteWithChildren = MembersIdRoute._addFileChildren(
  MembersIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MembersIdRoute: MembersIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
